name: Build & Test
on:
  push:
    branches:
      - master
      - pure_c_scanner
  pull_request:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest, macos-latest, windows-latest]
      #fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: npm install
      - run: node_modules/.bin/tree-sitter test
      - uses: docker-practice/actions-setup-docker@master
      - run: node_modules/.bin/tree-sitter build-wasm
      - uses: actions/upload-artifact@v2
        with:
          name: wasm-file
          path: tree-sitter-foam.wasm
